### ISSUE TITLE
Just some questions about using this

### ISSUE THREAD

**Issue by xSASxZaros** [zecoxao/rebuild_database#1]
Hello - Does this rebuild the database without needing to reboot?
And do you know if it would work with the new SD2VITA adapters?

Also, would you be able to upload some screenshots (or maybe even a video?) of it being used? Thanks.

Regards.

**Comment by zecoxao** [comment]
this always rebuilds the database and reboots, by using 3 different methods.

**Comment by zecoxao** [comment]
sorry, but i only use one of the options to rebuild database. 
there are three ways:
deleting id.dat
deleting act.dat
writing a file with a magic inside to rebuild using sony's way(what i do, and the recommended option)
